### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by behl1** [bovard/google-app-engine-react-backbone#1]
Nothing shows up as main.js 404's. Gulp never actually exits after finishing it's tasks. Do you think it might have to do with a version mismatch?

**Comment by bovard** [comment]
Thanks for pointing that out! I had the entry point wrong for browserify. Fixed in https://github.com/bovard/google-app-engine-react-backbone/commit/272b42801d3c74155ff689f2535e04f8e0eb5a82

Note that gulp should run every time you change a jsx file. If you want it just to run once you should run `gulp browserify`

**Comment by behl1** [comment]
Thanks!
